### ISSUE TITLE
Why firefox is not supported?

### ISSUE THREAD

**Issue by parrycima** [henripar/scrollbar#11]
Do you think in future to include firefox as well?

**Comment by dborsukov** [comment]
Scrollbar styling in Firefox is very limited. AFAIK, you can only change width and color.

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars#css.properties.scrollbar-width
