### ISSUE TITLE
A copy of scrollbar.app

### ISSUE THREAD

**Issue by zerosoul** [henripar/scrollbar#16]
I made a copy of scrollbar.app for learning, with more setting, more smooth UX.
https://sinqi.tools/scrollbar
![image](https://github.com/henripar/scrollbar/assets/2985895/da3133f1-ce83-45b2-9871-761312acecc1)

**Comment by henripar** [comment]
Looks great! 👍 

I'll close the issue though, since this is not anything that requires action to scrollbar.app
