### ISSUE TITLE
Scroll Bar Breaks in Chrome 121+ 

### ISSUE THREAD

**Issue by sahillangoo** [henripar/scrollbar#17]
Now that Chrome 121 has dropped to stable, that’s changed. The presence of one of the new properties like scrollbar-color overrides the usage of the pseudo elements. So if you were styling scroll bar, all the sudden it’s likely that your scrollbars looked a bit different, because the styling possibilities are much more limited with the standardized properties.

[reference ](https://frontendmasters.com/blog/heads-up-on-custom-scrollbars-chrome-is-supporting-the-standard-now-which-overrides-the-old-pseudo-elements/)

**Comment by henripar** [comment]
Thanks for raising this @sahillangoo ! 

I moved `scrollbar-color` property into `@supports not selector(::-webkit-scrollbar)` block so it wont override webkit properties in Chrome and you can still have a bit more flexibility in scrollbar styling vs. using just the standard `scrollbar-color` and `scrollbar-width` properties for Chrome and Safari.

Not the perfect solution but I think it's the best option for now.
