### ISSUE TITLE
Doesn't work in Chrome on Mac

### ISSUE THREAD

**Issue by brombomb** [henripar/scrollbar#2]
![image](https://user-images.githubusercontent.com/1136944/222787596-87fdcf80-d049-432e-aef1-43663f98034c.png)

* Chrome Version 110.0.5481.177 (Official Build) (arm64)
* ![image](https://user-images.githubusercontent.com/1136944/222787744-3f71b361-1852-4b08-b92b-6b4b2448c05e.png)

I thought it might be my scrollbar settings in system preferences
![image](https://user-images.githubusercontent.com/1136944/222788011-3fda7e04-de34-4de1-aa51-dedbc94b3def.png)

but checking in Firefox correctly colored the scrollbars.
![image](https://user-images.githubusercontent.com/1136944/222788225-9a9b2363-0ad1-41a4-a9b7-d4b998eb6272.png)

**Comment by henripar** [comment]
Hey,

Thanks for the feedback. Thats quite surprising.

I just tested on macOS Ventura 13.1 and the same version of Chrome as you and at least for me that works fine.

OS version shouldn't affect on this though. Do you have any browser extension installed that might mess up the styling?

**Comment by brombomb** [comment]
Yup I sure did! "Night Eye" which applies a dark theme to websites that don't support their own.  It consistently messes things up and I have to toggle it off more than I should.
